// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Gtu7YHLxf8kFNKZNBvxJnxqB6sWrrP4',
    appId: '1:21474109129:web:50a752ee97aa790dc0cf18',
    messagingSenderId: '21474109129',
    projectId: 'quizproject-ce30a',
    authDomain: 'quizproject-ce30a.firebaseapp.com',
    storageBucket: 'quizproject-ce30a.firebasestorage.app',
    measurementId: 'G-CXJCCP2GGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnw88l0Z5rKx8jqqIG3jKCLIPFfHsLQCo',
    appId: '1:21474109129:android:4956acbb40f6e205c0cf18',
    messagingSenderId: '21474109129',
    projectId: 'quizproject-ce30a',
    storageBucket: 'quizproject-ce30a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-yf4JoNOlPK7o1sRJYpdebLbruCbFQg',
    appId: '1:21474109129:ios:9e11dd95774ef3b3c0cf18',
    messagingSenderId: '21474109129',
    projectId: 'quizproject-ce30a',
    storageBucket: 'quizproject-ce30a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC-yf4JoNOlPK7o1sRJYpdebLbruCbFQg',
    appId: '1:21474109129:ios:9e11dd95774ef3b3c0cf18',
    messagingSenderId: '21474109129',
    projectId: 'quizproject-ce30a',
    storageBucket: 'quizproject-ce30a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Gtu7YHLxf8kFNKZNBvxJnxqB6sWrrP4',
    appId: '1:21474109129:web:49604d953d5636fec0cf18',
    messagingSenderId: '21474109129',
    projectId: 'quizproject-ce30a',
    authDomain: 'quizproject-ce30a.firebaseapp.com',
    storageBucket: 'quizproject-ce30a.firebasestorage.app',
    measurementId: 'G-55S0PEE794',
  );
}
